config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  post '/sendgrid', action: :sendgrid_webhooks, controller: "pages"

  resources :messages, only: :create
  resources :experiences, only: %i[index new create edit update destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cv.rb
class Cv < ApplicationRecord
  has_one_attached :photo
  attr_accessor :remove_photo
  after_save { photo.purge if remove_photo == '1' }
end

app/models/experience.rb
class Experience < ApplicationRecord
  validates :company, :role, :category, :description, presence: true
  validates :category, inclusion: { in: ["Travail", "Études", "Centres d'intérêt"] }
  validate :end_date_after_start_date
  has_one_attached :photo
  attr_accessor :remove_photo
  after_save { photo.purge if remove_photo == '1' }

  def category_enum
    ["Travail", "Études", "Centres d'intérêt"]
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "La date de début doit être après la date de fin") if end_date < start_date
  end
end

app/models/message.rb
class Message < ApplicationRecord
  MAILREGEX = /\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b/
  validates :name, :subject, :content, presence: true
  validates :email, format: { with: MAILREGEX }
end

app/models/resume.rb
class Resume < ApplicationRecord
  validates :description, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :category, inclusion: { in: ["Technologies", "Communication", "Soft Skills"] }
  validates :priority, inclusion: { in: (1..10).to_a }

  def category_enum
    ["Technologies", "Communication", "Soft Skills"]
  end

  def priority_enum
    (1..10).to_a
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_experience, only: %i[edit update destroy]
  def index
    @experiences = Experience.all.order('start_date desc')
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    if @experience.save
      redirect_to root_url, notice: 'Expérience ajoutée'
    else
      render :new, notice: 'Informations incorrectes'
    end
  end

  def edit; end

  def update
    if @experience.update(experience_params)
      redirect_to experiences_path, notice: 'Expérience modifiée'
    else
      render :edit, notice: 'Informations incorrectes'
    end
  end

  def destroy
    @experience.destroy
    redirect_to experiences_path, notice: "L'expérience' a été supprimée"
  end

  private

  def experience_params
    params.require('experience').permit(
      :start_date,
      :end_date,
      :company,
      :type,
      :role,
      :description,
      :company_logo_url
    )
  end

  def set_experience
    @experience = Experience.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :create
  def create
    @message = Message.new(message_params)

    if @message.valid?
      @message.save
      MessageMailer.contact(@message).deliver_later
      redirect_to root_url(anchor: 'contact'), notice: "Merci pour votre message, je vous répondrai dès que possible !"
    else
      redirect_to root_url(anchor: 'contact'), notice: 'Informations incomplètes'
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :subject, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :sendgrid_webhooks]
  protect_from_forgery except: [:sendgrid_webhooks]

  def home
    @experiences = Experience.all.order("start_date desc")
    @message = Message.new
  end

  def sendgrid_webhooks
    params["_json"].each do |payload|
      Message.create(
        subject: "Sendgrid response",
        content: "#{payload["smtp-id"]}_#{payload["event"]}",
        name: "SG_WEBHOOK",
        email: ENV["DEVELOPER_EMAIL_ADDRESS"]
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/experiences/edit.html.erb
<div class="new-experience-container mt-5 col-md-6 col-sm-12 mx-auto">
  <div class="new-experience-form-container text-center bg-white p-3 border">
    <div class="d-flex justify-content-between align-items-center mb-2 border-bottom">
      <h1 class='new-experience-container__title text-center' style='font-size: 1rem'><strong>Modifier une expérience</strong></h1>
      <%= link_to "Retour à la liste", experiences_path %>
    </div>
    <%= simple_form_for @experience, method: :patch do |f| %>
      <div class="form-inputs text-justify">
        <%= f.input :company, placeholder: "Nom de l'entreprise", label: false %>
        <%= f.input :description, placeholder: "Description de l'experience", label: false %>
        <%= f.input :role, placeholder: "Poste tenu", label: false %>
        <%= f.input :category, placeholder: "Quel type d'experience ?", label: false,
          collection: ["Travail" "Études" "Centres d'intérêt"] %>
        <%= f.input :current, label: "Poste actuel ?" %>
        <%= f.input :start_date, as: :string, placeholder: 'Date de début', input_html: { class: "datepicker" }, label: false %>
        <%= f.input :end_date, as: :string, placeholder: 'Date de fin', input_html: { class: "datepicker" }, label: false %>
        <%= f.submit 'Valider', class: 'btn-violaine-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/experiences/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="bg-white border d-flex align-items-center justify-content-between p-4">
        <h1 style='font-size: 1rem'><strong>Liste des expériences</strong></h1>
        <%= link_to 'Retour au site', root_url %>
      </div>
      <div class="bg-white border p-3 my-1"><em>Expériences Professionnelles</em></div>
      <% @experiences.where('category = ?', 'Travail').each do |experience| %>
        <% @experience = experience %>
        <%= render 'shared/index-experience-card', object: @experience %>
      <% end %>
      <div class="bg-white border p-3 my-1"><em>Formation</em></div>
      <% @experiences.where('category = ?', 'Études').each do |experience| %>
        <% @experience = experience %>
        <%= render 'shared/index-experience-card', object: @experience %>
      <% end %>
      <div class="bg-white border p-3 my-1"><em>Centres d'intérêt</em></div>
      <% @experiences.where('category = ?', 'Bénévolat').each do |experience| %>
        <% @experience = experience %>
        <%= render 'shared/index-experience-card', object: @experience %>
      <% end %>
    </div>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="new-experience-container mt-5 col-md-6 col-sm-12 mx-auto">
  <div class="new-experience-form-container text-center bg-white p-3 border">
    <div class="d-flex justify-content-between align-items-center mb-2 border-bottom">
      <h1 class='new-experience-container__title text-center' style='font-size: 1rem'><strong>Ajouter une expérience</strong></h1>
      <%= link_to "Retour au site", root_url %>
    </div>
    <%= simple_form_for @experience do |f| %>
      <div class="form-inputs text-justify">
        <%= f.input :company, placeholder: "Nom de l'entreprise", label: false %>
        <%= f.input :description, placeholder: "Description de l'experience", label: false %>
        <%= f.input :role, placeholder: "Poste tenu", label: false %>
        <%= f.input :category, placeholder: "Quel type d'experience ?", label: false,
          collection: %w[Travail Études Bénévolat] %>
        <%= f.input :current, label: "Poste actuel ?" %>
        <%= f.input :start_date, as: :string, placeholder: 'Date de début', input_html: { class: "datepicker" }, label: false %>
        <%= f.input :end_date, as: :string, placeholder: 'Date de fin', input_html: { class: "datepicker" }, label: false %>
        <%= f.submit 'Valider', class: 'btn-violaine-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <title>Violaine Quinchon | Portfolio</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/banner' %>
<%= render 'shared/resume' %>
<div class="container">
  <%= render 'shared/experiences' %>
</div>
<%= render 'shared/cv-button' %>
<%= render 'shared/skills' %>
<%= render 'shared/new-message' %>
<%= render 'shared/footer' %>

app/views/shared/_banner.html.erb
<div class="banner-color">
  <div class="banner-violaine" style="background-image: url(<%= asset_path 'me.svg' %>)">
    <div class="container justify-content-center">
      <div class="banner-violaine__title" data-aos="fade" data-aos-delay="50">
        <div class="p-3 text-center">
          <h1><%= User.first.first_name %> <strong><%= User.first.last_name %></strong></h1>
          <p>Responsable Communication Interne</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cv-button.html.erb
<% if Cv.count> 0 %>
  <div class="cv-button--container">
    <%= link_to "Voir mon cv" , rails_blob_path(Cv.last.photo, only_path: true), target: "_blank" ,
      class: "btn-violaine-secondary cv-button" %>
  </div>
<% end %>

app/views/shared/_experience-card.html.erb
<div class="row my-3 experience-card" data-aos="fade-up" data-aos-delay="50">
  <div class="col-3 experience-card__left">
    <div class="experience-card__left__year">
      <p><%= @experience.start_date.year %> -
        <% if @experience.current %>
          Aujourd'hui</p>
        <% else %>
          <%= @experience.end_date.year %></p>
        <% end %>
    </div>
    <% if @experience.photo.attachment %>
      <%= cl_image_tag @experience.photo.key, height: 70, width: 70, crop: :fill, alt: "#{@experience.company}-logo" %>
    <% elsif @experience.company_logo_url %>
      <%= image_tag @experience.company_logo_url, alt: "#{@experience.company}-logo", width: 70, height: 70, crop: :fill %>
    <% else %>
      <div></div>
    <% end %>

  </div>
  <div class="col-9 border-left">
    <div class="experience-card__right">
      <h1 class='experience-card__right__company'><%= @experience.company %></h1>
      <p class='experience-card__right__role'><em><%= @experience.role %></em></p>
      <p class='experience-card__right__description'><%= @experience.description %></p>
    </div>
  </div>
</div>

app/views/shared/_experiences.html.erb
<div class="experiences-container py-5" id='experiences'>
  <div class="text-center p-3 my-3 experiences__header" data-aos="fade-right" data-aos-delay="50">Expériences Professionnelles</div>
  <% @experiences.where('category = ?', 'Travail').each do |experience| %>
    <% @experience = experience %>
    <%= render 'shared/experience-card', object: @experience %>
  <% end %>
  <div class="text-center p-3 my-3 experiences__header" data-aos="fade-right" data-aos-delay="50">Formation</div>
  <% @experiences.where('category = ?', 'Études').each do |experience| %>
    <% @experience = experience %>
    <%= render 'shared/experience-card', object: @experience %>
  <% end %>
  <div class="text-center p-3 my-3 experiences__header" data-aos="fade-right" data-aos-delay="50">Centres d'intérêt</div>
  <% @experiences.where('category = ?', "Centres d'intérêt").each do |experience| %>
    <% @experience = experience %>
    <%= render 'shared/experience-card', object: @experience %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-violaine py-4 mx-auto px-auto">
  <div class="container">
    <div class="row align-items-baseline">
      <div class="col-lg-2 col-10 col-sm-6 col-md-2 footer-text border-left px-auto mx-auto">
        <strong>MENU</strong>
        <br>
        <a class='footer-link' href="#">
          Accueil
        </a>
        <br>
        <a class='footer-link' href="#apropos">À propos</a>
        <br>
        <a class='footer-link' href="#experiences">Expériences</a>
        <br>
        <a class='footer-link' href="#contact">Contact</a>
      </div>
      <div class="col-lg-3 col-10 col-sm-6 col-md-4 footer-text border-left px-auto mx-auto">
        <strong>ADMINISTRATION</strong>
        <br>
        <% if user_signed_in? %>
          <%= link_to 'Administration', rails_admin_path, class: 'footer-link' %>
          <br>
          <em><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "footer-link" %></em>
        <% else %>
          <%= link_to 'Admin', new_user_session_path, class: 'footer-link' %>
        <% end %>
      </div>
      <div class="col-lg-4 col-10 col-sm-6 col-md-5 footer-text border-left px-auto mx-auto">
        <strong>CONTACT</strong>
        <br>
        <%= User.first.first_name + " " + User.first.last_name %>
        <br>
        <em>Responsable communication interne</em>
        <br>
        <a href="mailto:<%= User.first.email %>" class="footer-link" target="_blank"><%= User.first.email %></a>
        <br>
        <a href="tel:+33664187470" class='footer-link'><i class="fas fa-mobile-alt" target="_blank"></i> - 06 64 18 74 70</a>
        <br>
        <a href="https://www.linkedin.com/in/violainequinchon-internalcoms/" class='footer-link' target="_blank"><i class="fab fa-linkedin"></i> - Linkedin</a>
        <br>
        <a href="https://www.instagram.com/tete_a_terre/" class='footer-link' target="_blank"><i class="fab fa-instagram"></i> - Instagram</a>
        <br>
        <a href="https://twitter.com/quinsharer" class='footer-link' target="_blank"><i class="fab fa-twitter"></i> - Twitter</a>

      </div>
      <div class="col-lg-3 col-10 col-sm-6 col-md-4 footer-text border-left px-auto mx-auto">
        <p>Un problème sur le site ? Contactez
          <a href="mailto:<%= ENV["DEVELOPER_EMAIL_ADDRESS"] %>" class="footer-link" style="text-decoration: underline">
            <%= ENV["DEVELOPER_EMAIL_ADDRESS"] %>
          </a>
      </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_index-experience-card.html.erb
<div class="bg-white border d-flex align-items-center justify-content-between p-3">
  <div class="experience-card__infos-left col-10">
    <h1 style='font-size: 1rem'><strong><%= @experience.company %></strong></h1>
    <div class="d-flex">
      <p><%= @experience.start_date.year %> -
        <% if @experience.current %>
          Aujourd'hui</p>
        <% else %>
          <%= @experience.end_date.year %></p>
        <% end %>
    </div>
    <p><em><%= @experience.role %></em></p>
    <p><%= @experience.description %></p>
  </div>
  <div class="d-flex col-1">
    <%= link_to experience_path(@experience), data: { confirm: 'Veux-tu vraiment supprimer ce projet ?' }, method: :delete do %>
      <i class="fas fa-trash-alt pr-2"></i>
    <% end %>
    <%= link_to edit_experience_path(@experience) do %>
      <i class="far fa-edit"></i>
    <% end %>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">
<%= favicon_link_tag 'icons/favicon-16x16.png' %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-orange">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Accueil", "#", class: "nav-link mr-5" %>
          </li>
          <li class="nav-item">
            <%= link_to "À Propos", "#apropos", class: "nav-link mr-5" %>
          </li>
          <li class="nav-item">
            <%= link_to "Expériences", "#experiences", class: "nav-link mr-5" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", "#contact", class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new-message.html.erb
<div class="contact-container">
  <div class="container">
    <div class="presentation-card d-flex justify-content-between align-items-center py-5" id='contact'>
      <div class="new-message-form-container p-3">
        <div class="mb-2">
          <h1 class="new-message-form-container__title pb-3 pl-3">Contact</h1>
        </div>
        <%= simple_form_for @message, url: messages_path, id: 'myform' do |f| %>
          <div class="form-inputs">
            <div class="form-row">
              <div class="col-5">
                <%= f.input :name, placeholder: 'Nom...', label: false %>
              </div>
              <div class="col-7">
                <%= f.input :email, placeholder: 'Email...', label: false  %>
              </div>
            </div>
            <%= f.input :subject, placeholder: 'Sujet du message...', label: false  %>
            <%= f.input :content, placeholder: 'Votre message...', label: false, input_html: { rows: 4 } %>
          </div>
          <%= f.submit 'Envoyer le message', class: 'btn-violaine-primary' %>
        <% end %>
      </div>
      <div class='presentation-card__image pl-5' data-aos="fade-left" ><%= image_tag "chat_person.svg", alt: "chat", width: '100%' %></div>
    </div>
  </div>
</div>

app/views/shared/_resume.html.erb
<div class="skills-container" id="apropos">
  <div class="container py-5 col-10 col-lg-7">
    <div class="text-center mb-3 pb-2 experiences__header" data-aos="fade-right" data-aos-delay="50">À propos</div>
    <div class="row justify-content-center">
      <p style="text-align: justify;" class="px-3">
        <%= Resume.last.description %>
      </p>
    </div>
  </div>
</div>

app/views/shared/_skills.html.erb
<div class="skills-container">
  <div class="container py-3">
    <div class="text-center p-3 my-3 experiences__header" data-aos="fade-right" data-aos-delay="50">Compétences</div>
    <div class="row justify-content-center">
      <div class="col-lg-4 col-sm-6 col-10">
        <div class="skills-card p-4">
          <%= image_tag "team_work.svg", alt: "team_work", width: '100%', class: 'skills-card__image mb-3' %>
          <% comms = Skill.where(category: "Communication").order(:priority) %>
          <h1><%= comms.first.category %></h1>
          <% comms.each do |com| %>
            <p><%= com.name %></p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6 col-10">
        <div class="skills-card p-4">
          <%= image_tag "team_connect.svg", alt: "team_work", width: '100%', class: 'skills-card__image mb-3' %>
          <% techs = Skill.where(category: "Technologies").order(:priority) %>
          <h1><%= techs.first.category %></h1>
          <% techs.each do |tech| %>
            <p><%= tech.name %></p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6 col-10">
        <div class="skills-card p-4">
          <%= image_tag "gallery.svg", alt: "team_work", width: '100%', class: 'skills-card__image mb-3' %>
          <% softs = Skill.where(category: "Soft Skills").order(:priority) %>
          <h1><%= softs.first.category %></h1>
          <% softs.each do |soft| %>
            <p><%= soft.name %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>